title: Malaria Cell Classification
description: AI-powered malaria detection using convolutional neural networks
author: AI4ALL Malaria Team
url: "https://ludafieno.github.io"
baseurl: "/ai4all-malaria.github.io"

# Build settings
markdown: kramdown